window:
  dimensions:
    columns: 222
    lines: 47
  padding:
   x: 10
   y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.99
  decorations: None
  

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: MesloLGS Nerd Font
    style: Regular
  bold:
    family: MesloLGS Nerd Font
    style: Bold
  italic:
    family: MesloLGS Nerd Font
    style: Italic
  bold_italic:
    family: MesloLGS Nerd Font
    style: Bold Italic
  size: 9

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '0x292b49'
    foreground: '0xabb2bf'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xabb2bf'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xffffff'

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
